version: '3.3'
services:
  php:
    build: 'php'
    volumes:
      - './src:/var/www/code'
      - './conf/php.ini:/usr/local/etc/php/php.ini'
  nginx:
    build: 'docker/nginx'
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/code'

  database:
    image:  mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ma_db
      - MYSQL_USER=mon_user
      - MYSQL_PASSWORD=secret!

  adminer:
    image:  adminer
    ports:
      - '8081:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=barde